require: rubocop-rspec

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FileName:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
